### ISSUE TITLE
Pending action items

### ISSUE THREAD

**Issue by gtmsingh** [KishanKharwar/inventory-management-system#1]
- [x] Output CSV related changes:
  - [x] Error output to show "Please correct quantities" as first line and the next n-lines will show item with it's incorrect quantities
  - [x] If all validation succeeds, the output should be the total amount paid. Note: maintain a hashmap for card number to total amount to be charged, so that in case in future if it is required to be output-ed, we can do that easily.
- [x] Initial input of card numbers to cards table
- [x] Initial configuration file for providing which category can be shopped to what max value.
- [x] Readme:
  - [x] CLI command for executing the program
  - [x] Design patterns used and where?

**Comment by KishanKharwar** [comment]
done
